{% set name = "ONT_SimSig" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # path: ../
  git_rev: v1.0.0
  git_url: https://github.com/JannesSP/{{ name|lower }}.git

advice.detachedHead: false

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python>=3.11
    - numpy>=1.24
    - setuptools
  # host:
  #   - python>=3.11
  #   - h5py>=3.8
  #   - biopython>=1.81
  #   - matplotlib>=3.7
  #   - numpy>=1.23
  #   - scipy>=1.10
  #   - pandas>=1.5
  #   - seaborn>=0.12
  run:
    - python>=3.11
    - h5py>=3.8
    - biopython>=1.81
    - matplotlib>=3.7
    - numpy>=1.23
    - scipy>=1.10
    - pandas>=1.5
    - seaborn>=0.12

test:
  imports:
    - {{ name|lower }}
  commands:
    - ont_simsig --help

about:
  home: https://github.com/JannesSP/{{ name|lower }}
  license: MIT License
  license_family: MIT
  license_file: LICENSE 
  summary: "Simulation of Oxford Nanopore Technologies RNA sequencing signals"

# conda mambabuild conda/ --numpy 1.24 --python 3.11