{% set name = "ont_simsig" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # path: ../
  git_rev: '1.0.0'
  git_url: https://github.com/JannesSP/{{ name|lower }}.git

advice.detachedHead: false

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python>=3.11
    - numpy>=1.24
    - setuptools
  run:
    - python>=3.11
    - h5py>=3.8
    - biopython>=1.81
    - matplotlib>=3.7
    - numpy>=1.23
    - scipy>=1.10
    - pandas>=1.5
    - seaborn>=0.12
    # - hdf5plugin>=3.3.1
    # - ont_vbz_hdf_plugin>=1.0.1

test:
  imports:
    - {{ name|lower }}
  commands:
    - ont_simsig --help

about:
  home: https://github.com/JannesSP/{{ name|lower }}
  license: GNU General Public License v3.0
  license_family: GPL
  license_file: LICENSE 
  summary: "Simulation of Oxford Nanopore Technologies RNA sequencing signals"

# conda mambabuild conda/ --numpy 1.24 --python 3.11